POST http://localhost:9090/api/v1/users
Content-Type: application/json

{
  "email": "choicore@github.com",
  "password": "1234",
  "firstName": "Jae-hyeong",
  "lastName": "Choi",
  "nickname": "choicore",
  "gender": "M",
  "birthDate": "1993-09-22"
}

###